# Generated by Django 4.2.5 on 2023-10-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
    ]
